# Generated by Django 5.1 on 2024-09-11 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Message role, 'user' if role is True 'assistant' if False else 'system'",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(db_index=True, help_text="Message content"),
                ),
                (
                    "is_starred",
                    models.BooleanField(
                        default=False, help_text="Designates if the message is saved"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="Message chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Message owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
